# Name of workflow as seen in Github actions tab
name: main-build-and-deploy
# Run workflow only on push to main branch
on:
  push:
    branches:
      - main
jobs:
  # To build the project
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: npm --prefix client install client
      - name: Building project
        run: npm --prefix client run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to S3 bucket
        run: aws s3 sync ./client/build/ s3://game7-cotrib --delete

  # build-server:
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Checkout source code
  #     uses: actions/checkout@v2

  #   - name: Generate deployment package
  #     run: zip -r deploy.zip . -x '*.git*' -x './client/*'

  #   - name: Deploy to EB
  #     uses: einaregilsson/beanstalk-deploy@v21
  #     with:
  #       aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       application_name: game7-exp
  #       environment_name: Game7exp-env
  #       use_existing_version_if_available: true
  #       version_label: 12345-1
  #       version_description: ${{github.SHA}}
  #       region: us-east-1
  #       deployment_package: deploy.zip

  deploy-server:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli
      
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init ${{ secrets.EB_APPLICATION_NAME }} --platform "Node.js 16 running on 64bit Amazon Linux 2" --region ${{ secrets.AWS_DEFAULT_REGION }}
          eb use ${{ secrets.EB_ENVIRONMENT_NAME }}
          eb setenv DB_HOST=${{ secrets.DB_HOST }} DB_PORT=${{ secrets.DB_PORT }} DB_USER=${{ secrets.DB_USER }} DB_NAME=${{ secrets.DB_NAME }} DB_PASS=${{ secrets.DB_PASS }}
          eb deploy
